image: node:18

stages:
  - test
  - build

cache:
  paths:
    - node_modules/

test:
  stage: test
  script:
    - npm install
    - npm test

build_docker:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker info
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
